<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260408133753 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create all tables with IF NOT EXISTS for safe re-run';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS establishment (id UUID NOT NULL, name VARCHAR(255) NOT NULL, place_id VARCHAR(255) NOT NULL, google_place_id VARCHAR(255) DEFAULT NULL, address VARCHAR(500) NOT NULL, alerts_enabled BOOLEAN NOT NULL, last_sync_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, google_account_id VARCHAR(255) DEFAULT NULL, google_location_id VARCHAR(255) DEFAULT NULL, google_access_token TEXT DEFAULT NULL, google_refresh_token TEXT DEFAULT NULL, google_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_DBEFB1EEDA6A219 ON establishment (place_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_DBEFB1EE7E3C61F9 ON establishment (owner_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS review (id UUID NOT NULL, google_author VARCHAR(255) NOT NULL, google_author_photo VARCHAR(500) DEFAULT NULL, rating INT NOT NULL, text TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, google_review_id VARCHAR(255) NOT NULL, is_read BOOLEAN NOT NULL, owner_reply TEXT DEFAULT NULL, google_reply_published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_published_to_google BOOLEAN DEFAULT NULL, google_review_name VARCHAR(500) DEFAULT NULL, establishment_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_794381C6B9F1B03 ON review (google_review_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_794381C68565851 ON review (establishment_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS review_analysis (id UUID NOT NULL, positive_themes JSON NOT NULL, negative_themes JSON NOT NULL, action_suggestion TEXT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, establishment_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_23714E3B8565851 ON review_analysis (establishment_id)');
        $this->addSql('CREATE TABLE IF NOT EXISTS "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, alerts_enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('DO $$ BEGIN ALTER TABLE establishment ADD CONSTRAINT FK_DBEFB1EE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE; EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        $this->addSql('DO $$ BEGIN ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE; EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        $this->addSql('DO $$ BEGIN ALTER TABLE review ADD CONSTRAINT FK_794381C68565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE; EXCEPTION WHEN duplicate_object THEN NULL; END $$');
        $this->addSql('DO $$ BEGIN ALTER TABLE review_analysis ADD CONSTRAINT FK_23714E3B8565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE; EXCEPTION WHEN duplicate_object THEN NULL; END $$');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE establishment DROP CONSTRAINT IF EXISTS FK_DBEFB1EE7E3C61F9');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT IF EXISTS FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT IF EXISTS FK_794381C68565851');
        $this->addSql('ALTER TABLE review_analysis DROP CONSTRAINT IF EXISTS FK_23714E3B8565851');
        $this->addSql('DROP TABLE IF EXISTS establishment');
        $this->addSql('DROP TABLE IF EXISTS reset_password_request');
        $this->addSql('DROP TABLE IF EXISTS review');
        $this->addSql('DROP TABLE IF EXISTS review_analysis');
        $this->addSql('DROP TABLE IF EXISTS "user"');
    }
}
