parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    App\Service\GooglePlacesService:
        arguments:
            $apiKey: "%env(GOOGLE_PLACES_API_KEY)%"

    App\Service\LlmService:
        arguments:
            $apiKey: "%env(OPENAI_API_KEY)%"
